### ISSUE TITLE
Redirect to Login Page Fails

### ISSUE THREAD

**Issue by TheYorkshireDev** [POPWorldMedia/POPForums#101]
When you try navigating to a restricted area of the forum such as `/Forums/Admin` as an unauthenticated user the forum attempts to redirect you to the login page. However, the page reference does not exist because the URI is missing the `Forums` area prefix.

### Steps to Reproduce
As an unauthenticated user go to: https://popforumsdev.azurewebsites.net/Forums/Admin

**Expected Result**

To be redirected to the login page with the url: https://popforumsdev.azurewebsites.net/Forums/Account/Login?ReturnUrl=%2FForums%2FAdmin because I am not logged in.

**Actual Result**
I am redirect to the url https://popforumsdev.azurewebsites.net/Account/Login?ReturnUrl=%2FForums%2FAdmin which returns a 404.

_NOTE_ the missing `/Forums/` in the URL

**Site Note:** Should 404s on the demo site be using the `NotFound.cshtml` in `PopForums.Mvc`?

**Comment by jeffputz** [comment]
Isn't this the same behavior as in classic MVC and configurable?

**Comment by TheYorkshireDev** [comment]
Yes, it is. I just thought it would be nice to update the demo site to redirect correctly. I am aware that this may not be a requirement for all sites using PopForums.

Feel free to close this if you don't think the demo site should be updated. Also should the demo site have the error pages hooked up or not?

**Comment by jeffputz** [comment]
Right on. Yeah, I don't know that I want to shortcircuit any behavior set by a parent app, so I think I'll just defer it to whatever the developer needs/wants.
