### ISSUE TITLE
Image upload in posts

### ISSUE THREAD

**Issue by tharris9d** [POPWorldMedia/POPForums#109]
We have a requirement to upload images vs linking to them. Has anyone added the upload capability using TinyMCE in Pop Forums?

**Comment by jeffputz** [comment]
I haven't seen it, but I haven't really looked hard at all of the forks. I imagine we'd have to roll something custom there, because I assume from a persistence standpoint it would just lump all uploads together, not associated with users or posts.

**Comment by tharris9d** [comment]
![pf post database](https://user-images.githubusercontent.com/217445/51859463-056a7580-22ec-11e9-945f-5e11ac4d4276.PNG)
Hi Jeff, It looks like when I change TinyMCE to allow uploads in PopForums.js and add a simple function to the script it saves to the pf.post table, FULLTEXT field.  I attached a screenshot of the data. Am I missing something or will this work.

**Comment by jeffputz** [comment]
Interesting, I didn't know that was the default behavior, embedding images as data. I'm not sure how I feel about that, because the images then can't be cached when they're embedded in the HTML that way.

**Comment by tharris9d** [comment]
Jeff, I appreciate your quick response. I didn't think about the caching. Good point. It may work for us until I can write the file saving routines.  I am also porting the back end to Oracle. It should be fun....

**Comment by jeffputz** [comment]
@tharris9d Cool! Hopefully it involves simply writing a variation on the Sql project. Note that I'm working on converting all of the Sql repos to use Dapper at the moment, so that code will be fairly volatile for awhile.

**Comment by tharris9d** [comment]
Awesome news! Dapper will make it easier to connect with different db's.

**Comment by jeffputz** [comment]
Adding to v19 project. Will include storage to Azure blob and to database, configurable.

**Comment by tharris9d** [comment]
Thanks Jeff!
