### ISSUE TITLE
[QUESTION] PostgreSQL

### ISSUE THREAD

**Issue by nicotravassos** [POPWorldMedia/POPForums#113]
Hi @jeffputz,

How would I go by using PostgreSQL on POPForums?

**Comment by jeffputz** [comment]
You would have to at the very least do your own implementations of the repositories and supporting code in the PopForums.Sql project and then map those implementations using your own variation on the `AddPopForumsSql` extension method. I believe you can use Dapper with PostgreSQL, so it might largely come down to replacing the plumbing in the extension methods that deal in the command and connection objects (I'm assuming that PostgreSQL has their own implementations of DbCommand, etc.).

**Comment by nicotravassos** [comment]
Thanks for your feedback @jeffputz.
