### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by rodolphito** [POPWorldMedia/POPForums#127]
Hey, nice software you got here.

It seems that there are no user groups, I'll probably be trying to add them if there's no currently existing solution for it. This would be closely related to #86, groups could have private forums.

**Comment by rodolphito** [comment]
as an aside, is there any place where project coordination is done? Maybe a discord chat, or gitter, or slack?

**Comment by jeffputz** [comment]
I am the project, so there isn't much to coordinate.

Groups are roles. Create a role, add people to it, change the forum permissions to make it private or read only.

**Comment by rodolphito** [comment]
Oh, cool, thank you. Thanks for making this open source!
