### ISSUE TITLE
SQL 14 to 15 migration script

### ISSUE THREAD

**Issue by scottkdavis** [POPWorldMedia/POPForums#155]
I ran the 3 SQL scripts to setup the database. An index rename caused a failure. Adding this check before the last index creation in the 14to15 migration script will avoid the error.

IF IndexProperty(Object_Id('pf_TopicViewLog'), 'IX_pf_TopicViewLog', 'IndexId') IS NOT NULL
DROP INDEX [IX_pf_TopicViewLog] on [dbo].[pf_TopicViewLog]

**Comment by jeffputz** [comment]
Were you migrating from v14 to v15? If you weren't, you don't need to run any of those. The primary script (per the docs) can actually be run right from the app itself via setup.
