### ISSUE TITLE
Failed reply doesn't wire up failure message and tries to redirect anyway

### ISSUE THREAD

**Issue by senadburak** [POPWorldMedia/POPForums#160]
If I post reply one after previous, then I get an error ...**Topic/null**, that is the specified page is not found. Clearly, this is because of the **null** in paremeter value.

It is a bug I think

Rgds. SB

**Comment by jeffputz** [comment]
That's legit. I'll get a fix into the next release.

**Comment by jeffputz** [comment]
Weird, now I can't reproduce the error.
