### ISSUE TITLE
search

### ISSUE THREAD

**Issue by senadburak** [POPWorldMedia/POPForums#161]
Hi there,
initially the search service worked at my localhost as expected.
However, later on it completely failed. Don't know why?
I cahnge my PopForums.json with
    "Search": {
      "Url": "https://localhost:44319/",
      "Key": "99011A70D3D50D251B0A6141A97B40E7"
    },
but do not really understand it, ie. from where I get this Key value?

What should I do, thanks?

**Comment by jeffputz** [comment]
Which search provider are you using?

**Comment by senadburak** [comment]
Hi Jeff,

None. I am just testing the system as it is on your github.

The strange thing (perhaps I am wrong here)  is that sometimes work although I didn't change anything.

One thing I improved though: in your approach your Search is based on exact word or list of words that we have to enter into the Search box.

This is OK, but I was thinkin it will be better to have more flexibility here. This why I changed your SearchTopics method in SearchRepository.cs to:

public virtual async Task<Tuple<Response<List<Topic>>, int>> SearchTopics(string searchTerm, List<int> hiddenForums, SearchType searchType, int startRow, int pageSize)
		{
			var topicCount = 0;
			if (searchTerm.Trim() == string.Empty)
				return Tuple.Create(new Response<List<Topic>>(new List<Topic>()), topicCount);
			var topics = new List<Topic>();
			var wordArray = searchTerm.Split(new [] { ' ' });
			var wordList = new List<string>();
			var junkWords = await GetJunkWords();
			var alphaNum = SearchService.SearchWordPattern;
			for (var x = 0; x < wordArray.Length; x++)
			{
				foreach (Match match in alphaNum.Matches(wordArray[x]))
				{
					if (!junkWords.Contains(match.Value))
						//wordList.Add(match.Value);
                       					 // Senad
						wordList.Add(match.Value + "%");
				}
			}

...
And after this:

			for (int x = 0; x < words.Length; x++)
			{
				string xstring = x.ToString();
                			// Senad
				sb.Append(" JOIN (SELECT TOP 10000 TopicID, pf_TopicSearchWords.Rank FROM pf_TopicSearchWords 					WHERE SearchWord LIKE ");
				var param = "@w" + x;
...

It Works much better now for me, ie. If I Search for programming or programmer i can just type program and the Search will give me all references.

My two cents...

Q. How to use another Search provider, ie. ElastiSearch etc? Any example or info?

Thankyou for a great project!

Rgds. Senad

**Comment by jeffputz** [comment]
That change will kill your database on a large index, guaranteed. It will have to scan the entire index every time, which in even a small forum could be a million rows.

If you want more robust searching, I strongly recommend you use ElasticSearch or Azure Search.

**Comment by senadburak** [comment]
Thank you for the comments, I will get rid of what I done.

But, how to use the ElasticSearch? Do we need to have an Azure account, or even to host the forum on the Azure cloud?

Rgds. Senad

**Comment by jeffputz** [comment]
Setting up ES is beyond the scope of any documentation here, but to configure it at the forum end, look here:
https://github.com/POPWorldMedia/POPForums/wiki/Using-AwsKit-library#using-elasticsearch-for-search

ES can live anywhere. I run it on AWS because it's managed, and the app in Azure.

**Comment by senadburak** [comment]
Now I am not sure if I understand it at all.
The question is: can we just use the built-in search service as it is, or we have to use commercial Search services (Azure, ElasticSearc)?
I found from the source that the built-in search uses a timer, which constantly pushing delete an insert records into pf_TopicSearchWords table. I am just worried how this will affect the server in real time situations?

**Comment by jeffputz** [comment]
The built-in search just checks a queue on a timer, and if the queue has a message, it indexes that topic. You don't want that happening in the context of a web request, because it could take many seconds to complete. Slower SQL Azure plans will time out in large db's as well.

If you're worried about scale, the ideal is to use Azure Functions instead of the in-web-context background tasks, use Redis for caching (to run multiple nodes of the web app) and ElasticSearch or Azure Search for search.

**Comment by senadburak** [comment]
Can we eliminate the timer completelly?

Why not just update the pf_TopicSearchWords table after (and only after) a user click on Submit button on a new topic or reply?

In this way we will not reduce the size of the Search table, but it will drmatically reduce the traffic between the application and sql server and avoid unnecesseary tons of  inserts, delete etc

Rgds. SB

**Comment by jeffputz** [comment]
Because reindexing a long topic in the context of a web request could take a very long time. The user doesn't want to wait around for that. I'm telling you, on slow hardware, a topic with 100+ posts will take many seconds and block the resulting UI update. Running in Azure functions, I can show you on coasterbuzz.com instances where it can take 20 seconds or more.

There is no dramatic savings here. If the forum sits idle and no new posts are added, the timer checking the queue adds no overhead. Remember, most forums are 99.5% read-only in terms of traffic. There are no "unnecessary" inserts or deletes.

**Comment by senadburak** [comment]
Jeff,

I really appreciate your help and quick responses.

My uderstending of your discussion is that you do not recomend the built-in Search solution. Further, I learned that both, the Azure and ElasticSearch solutions are paid based services, and this is not acceptable for me right now.

This is why I am thinking now to get rid of the Search option whatsoever. Perhaps I should later think of the SQL Full-Text Search? I use it already, but the database is pretty small, cca 10,000 records, and it Works OK. But in case of Long topic... who knows.

**Comment by jeffputz** [comment]
Full text isn't terrible, but it's not particularly fast, and some free options simply don't have it available.

I use the built-in search on coasterbuzz.com, and it's good enough for keyword hits. AWS has a free tier for ES, and I'm going to experiment with that. You could also run it in a container, which is what I do locally.
