### ISSUE TITLE
Last Post

### ISSUE THREAD

**Issue by senadburak** [POPWorldMedia/POPForums#164]
Is there any way to get the last post in forums from the HomeController > Index() method?

The idea is to include the latest post in every forum on the home page as a link, so the visitors can click on it and go directly to the post?

**Comment by jeffputz** [comment]
That navigation doesn't make sense. You wouldn't know what you're going to. If you want to fork it and add to your own version, knock yourself out, but I'm not going to add it to the official build.

**Comment by senadburak** [comment]
The idea was to open the latest topic and then automatically scroll to the bottom of the screen (javascript).

However, if this doesn't make a sense to you, let us forget it.

**Comment by jeffputz** [comment]
Yeah, I don't think it's a logical navigation path. We have a lot of users who go to Recent, then the topic they want (via the new post icon) and then back to recent.
