### ISSUE TITLE
PopForum Admin dropdown not working

### ISSUE THREAD

**Issue by Orgbrat** [POPWorldMedia/POPForums#180]
I have a new ASP.NET Core 3.1 Razor Pages web application. I have added your PopForum nuget packages with associated files to the new web site using the PopForums.Sample project as my template. I have everything working  as expected except for the Admin navigation dropdown at top of admin pages. The button is there but it will not drop down.  I can manually enter the correct admin url and I am able to get to whatever page I need but the drop down does not work.  Can anyone help with this issue?

Orgbrat

**Comment by jeffputz** [comment]
Doesn't sound like Vue.js is loading. What does the browser console window say? Are your Grunt tasks running to build the front-end?

**Comment by Orgbrat** [comment]
The issue was popper.js.  The trick was using the using the bootstrap.bundle.min.js file which has popper included in it and removing the script tag where I was loading the popper.js file. Drop down works now.  :)
