### ISSUE TITLE
Allow option to rely entirely on 3rd-party OAuth2 and OIDC for sign-in

### ISSUE THREAD

**Issue by jeffputz** [POPWorldMedia/POPForums#183]
This probably has to come after #86. The use case is basically to rely on an OAuth source and auto-provision user accounts.
* The "sub" from the provider response will be associated with a PF account. If it doesn't exist, it will be created and use the email and name from the response. Password in theory won't be used, but a random one will be generated in the event the forum is ever converted to use its own auth.
* The response will be used to check the name of the user, and update it if it's changed.
* Configuration will include:
  * IsOAuthOnly (boolean determining it will use the external auth only)
  * Client ID
  * Client Secret
  * Base Login URL (for the provider)
  * Token URL
  * Admin claim name
  * Admin claim value (optional)
  * Moderator claim name
  * Moderator claim value (optional)
  * Scopes
* Some areas of admin will be disabled
* Some parts of profile editing will be disabled
* A new setup experience is necessary
  * `IsNewUserApproved = true`

**Comment by manuelxmarquez** [comment]
I have submitted a pull request where I added this feature. I really needed to add IdentityServer4 support but decided to split my change in case someone needs it with the existing external account support.

I have a branch which builds on top of this for IdentityServer4. It is quite a bit more complicated to get the logout feature to work and link back to IS for logout. I also set it up to use the token to get additional user claims which can be used to update the forum account and sync up all changes. All you need to do is override the AutoProvisionAccountService

https://github.com/manuelxmarquez/POPForums/tree/IdentityServer4

**Comment by jeffputz** [comment]
There are some things to think through here...
* I wouldn't put the setting in config, but rather settings. In a multi-tenant scenario (i.e., the commercial version), this would be configurable from admin.
* The implementation should be even simpler... instead you can set up an arbitrary OAuth2 provider (for which support already exists), leaving only the need to disable the login boxes and auto provision account creation (with the returned claims) instead of the local account association workflow. More importantly, _there's no need to tie it to any specific identity provider like IDS4_.
* What is the happy path for a newly created forum? Normally we create a local user for that. What happens if the admin no longer has an account with the identity provider?
