### ISSUE TITLE
DateTime parsing  on client in server localization, with DST

### ISSUE THREAD

**Issue by mcshaz** [POPWorldMedia/POPForums#188]
A suggestion for the next major release - bearing in mind the large proportion of the world's population who live in daylight savings zones do not live in Europe or Nth America:
Obviously in decoupling .net core from windows, some of the Windows registry functionality has been lost, however if you were willing to have a dependency on a package such as:

1. https://nodatime.org/
2. https://github.com/mj1856/TimeZoneConverter

You could then allow time zones to account for daylight saving outside US/Europe on any of the 3 supported operating systems.

It would be a major version change as the database would store a TimeZoneId rather than a offset & boolean. The entire change would not be trivial, but updating database fields to select the 1st northern hemisphere zone which matched the dates you currently use would be straight forward.

The dropdown list when setting up the database for the 1st time could limit the options to those on the hosting server, minimising problems with "timeZoneId not found" errors.

**Comment by jeffputz** [comment]
What locale do you want to accommodate? I would rather just augment the code to do that and not add a dependency.

**Comment by mcshaz** [comment]
No worries - I wanted to support NZ, but I can institute that myself. I have never seen the formula you use before for getting the nth or last Sunday of the month,  without using a 'DayOfWeek' property `(31 - (Math.Floor((double)localTime.Year * 5 / 4) + 1) % 7)` - that is great!

As an aside, I believe the logic for European daylight saving may be subtly wrong (potentially an argument for using a library) - the changeover I believe is at 01:00 UTC, not local time, so that all timezones within the EU swap simultaneously. You could change the IsUtcFunction similar to the code below:
```
//note using a double not int for the offset as about a billion people live in half hour UTC offsets!
private bool IsDaylightSaving(DateTime localTime, double utcOffset)
{
	DateTime startDate;
	DateTime endDate;
...
	if ((_utcOffset > -1) && (_utcOffset < 5))
	{
		// european dst
		startDate = new DateTime(localTime.Year, 3, Convert.ToInt32(31 - (Math.Floor((double)localTime.Year * 5 / 4) + 1) % 7), utcOffset + 1.0, 0, 0);
		endDate = new DateTime(localTime.Year, 10, Convert.ToInt32(31 - (Math.Floor((double)localTime.Year * 5 / 4) + 1) % 7), utcOffset + 1.0, 0, 0);
		return ((localTime > startDate) && (localTime < endDate));
	}
```

also please note (quoted from www.timeanddate.com)

> On March 26, 2019, the European Parliament voted in favor of removing Daylight Saving Time (DST) permanently. If the law comes into effect, 2021 may be the last time EU Member States and affiliated countries follow the seasonal clock change.
>Each Member State has until April 2020 to decide whether to remain permanently on “summer time” (DST) or to change their clocks back one final time to permanent standard time, also known as “winter time.”

**Comment by jeffputz** [comment]
@mcshaz  I couldn't tell you where the math came from. It's pretty old. I can tell you that the US calculation definitely works, since we annoyingly switched this weekend. If the EU does change, it's simple enough for people to uncheck the box. We already have some states here in the US that stopped using it (well, technically, permanently embraced the daylight time). I have a feeling it may all go away in the next few years.

Thank you for engaging, regardless!

**Comment by mcshaz** [comment]
another thought - what about serving the time in ISO8601 UTC and have client Javascript display local time. The server remains agnostic to the timezone the owner of the forum is in, and everyone sees times/dates in both their local timezone offset and their local timezone format - using toLocaleString with a Intl.DateTimeFormat. The string for Intl.DateTimeFormat is taken from:
```
const lang = window.navigator.languages 
   ? window.navigator.languages[0]
   : (window.navigator.language || window.navigator.browserLanguage || window.navigator.userLanguage || "en")
```

**Comment by jeffputz** [comment]
Well, the time is already sitting on the client as UTC is most cases, because every minute or so it calls back to get the language specific formatting for "5 minutes ago" and the like. We'd have to do some client-side localization to pull that off.

**Comment by mcshaz** [comment]
I'll give it a quick shot and you can see what you think in a pull request if you like. Do you have a browser support matrix?

**Comment by jeffputz** [comment]
@mcshaz Not IE, mostly. 😊 Don't go too nuts... I imagine a lot of this will fundamentally change at some point in the next year or two. I've optimized the crap out of the back end in the last couple of years, but largely neglected the front other than the admin experimentation.

**Comment by mcshaz** [comment]
dealt with in pull request #190 - see what you think. Please let me know if you want a bit of detail about what the code is doing and why. I haven't used jQuery in years - predominantly VueJs + vanilla ECMAScript 6 with trans-piling now days!

**Comment by jeffputz** [comment]
As I'm now revisiting the front-end stuff and componentizing all of the spaghetti script, it appears that browsers are smart enough now to take UTC and format it correctly _and_ figure out if the date fell in DST. Validated in a fiddle: https://jsfiddle.net/jeffyjonesx/d1vh5wzo/14/

This is so simple that I can probably send the format strings in the same way I'm handling initial user state for the "minutes ago" and "today/yesterday" stuff in the appropriate language. Then it's just a component to put everywhere there's a UTC already there.
