### ISSUE TITLE
feature request: upload files

### ISSUE THREAD

**Issue by mcshaz** [POPWorldMedia/POPForums#192]
It would be great to be able to upload files with administrator specified allowed file extensions - eg .docx .pdf

**Comment by jeffputz** [comment]
Need a lot more requirements for something like that. One of the concerns is storage. Streaming to SQL is fine and makes for a good portability story, but what happens at scale? Then you're better off using some kind of blob storage. The whole thing starts to go too far from the core purpose and into territory that other apps cover. Why not just link to Google Docs or SharePoint or whatever?

**Comment by mcshaz** [comment]
No worries
