### ISSUE TITLE
Error on first debug open

### ISSUE THREAD

**Issue by Caiiiiii** [POPWorldMedia/POPForums#203]
When i first time to debug this project, it show me `System.NullReferenceException:“Object reference not set to an instance of an object.”`,and it haapen at 
`		public static async Task UsingAsync(this DbConnection connection, Func<DbConnection, Task> action)
		{
			using (connection)
			{
				try
				{
					await connection.OpenAsync();
					await action(connection);     //    <------here
				}
				finally
				{
					connection.Close();
					connection.Dispose();
				}
			}
		}`

I dont konw how to fix this issues,many time to debug , i find the reason maybe this one : 
`Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool.`.pls tell me what should i do. thanks 👍 
![1590402482(1)](https://user-images.githubusercontent.com/25955671/82804791-81aba380-9eb5-11ea-9e5b-afa81fcf82ba.jpg)

**Comment by jeffputz** [comment]
If the connection times out, what do you think the problem is? It's not a bug.

**Comment by sevengh** [comment]
Hi, i have same problem. How to fix it?
