### ISSUE TITLE
this is a bug about website characters

### ISSUE THREAD

**Issue by Caiiiiii** [POPWorldMedia/POPForums#204]
when i use the resources.zh-TW.resx, it show me unicode characters  in "save" button on admin page.

i dont know why it work at index page,but not at admin page.

i google some sloutions ,and this is successful：
add into Startup.cs -> ConfigureServices method
`services.AddSingleton<HtmlEncoder>(HtmlEncoder.Create(allowedRanges: new[] { UnicodeRanges.BasicLatin, UnicodeRanges.CjkUnifiedIdeographs }));`

**Comment by jeffputz** [comment]
If you found a solution, then you should be good.
