### ISSUE TITLE
Controller.URL getting null at the Forum AccountController - Create action

### ISSUE THREAD

**Issue by abhishekbhalani** [POPWorldMedia/POPForums#219]
Hi,

Getting null value while calling Account Controller with Create New user account action..

![image](https://user-images.githubusercontent.com/1845707/107343267-2e32c180-6ae7-11eb-9825-0300ed81c987.png)

![image](https://user-images.githubusercontent.com/1845707/107343072-ffb4e680-6ae6-11eb-9999-c5d2cff37083.png)

Is anything missing in it ?

Thank you.

**Comment by jeffputz** [comment]
I can't repro. Do you have something else in your request pipeline that would mess with the request URL?
