### ISSUE TITLE
Rename auth policies for forum roles to avoid naming conflicts

### ISSUE THREAD

**Issue by abhishekbhalani** [POPWorldMedia/POPForums#229]
We have facing issue the conflict .netcore existing project policy name and popforum authorization policy name.

Is anyone have idea how to sorted out the policy name with user roles isssue.
old user roles as follows
admin => administrator
companyadmin => companyAdmin
and policy names are different.
on popforums we have admin & moderator role & same policynames.

How to use two different policy & authorization in single application.

Regards,
Abhi

**Comment by jeffputz** [comment]
This will be in the next release, but that release will target .NET 5, or maybe 6.

**Comment by jeffputz** [comment]
@abhishekbhalani just to be clear... the conflict is in the _policy_ and not the _role_ name assigned to the principal, right?

**Comment by jeffputz** [comment]
Closing this because author never responded to question.
