### ISSUE TITLE
AwardCalculationProcessor is Not Idempotent

### ISSUE THREAD

**Issue by NullPointer4096** [POPWorldMedia/POPForums#333]
**Description**:

The [AwardCalculationProcessor](https://github.com/POPWorldMedia/POPForums/blob/e27faa41e24895ef7cd10cd37c6ae28464d4b265/src/PopForums.AzureKit.Functions/AwardCalculationProcessor.cs#L28) function is an Azure QueueTrigger function that retries upon exceptions and function host errors. When it finds that the conditions for an award have been met, it issues the award through calling [_userAwardService.IssueAward()](https://github.com/POPWorldMedia/POPForums/blob/fcecca261922dbcef39aa01c75763b1dca6702db/src/PopForums/ScoringGame/AwardCalculator.cs#L71). Within this function, it first logs the award issuance in the database and then sends a notification to the user. However, if the function runtime crashes after updating the database but before sending the notification, the [_userAwardService.IsAwarded()](https://github.com/POPWorldMedia/POPForums/blob/fcecca261922dbcef39aa01c75763b1dca6702db/src/PopForums/ScoringGame/AwardCalculator.cs#L58) condition check will prevent sending the notification upon future retries.

**Issue**:

The AwardCalculationProcessor function does not ensure idempotency when the function runtime crashes (due to software, hardware, or network errors) after updating the database but before sending the user notification. This may result in users not receiving award notifications when the function is retried.

**Suggested fix**:

Making the AwardCalculationProcessor function fully idempotent may be challenging. However, as a workaround, we can switch the order of the database logging and user notification steps. By sending the notification before updating the database, we can at least ensure that the user receives at least one notification even if the function runtime crashes and restarts. This approach improves the user experience and reduces the likelihood of missed notifications.

**Comment by jeffputz** [comment]
This is by design. Notifications are a secondary concern. It doesn't matter if the notification happens, issuing the award is the most important thing.

Also, what "crashing" are you experiencing? This is about as far out an edge case as you can get.

**Comment by NullPointer4096** [comment]
Thank you for your response. I understand that issuing the award is the primary concern, and notifications are secondary. My intention was to point out the potential issue with idempotency in the AwardCalculationProcessor function, which could affect the user experience in edge cases. If logging the award in the database happens first, the user would either receive no notification or one notification. However, if the notification is sent first, the user would be guaranteed to receive at least one notification.

Regarding the "crashing" I mentioned, I agree that it's an edge case and might only happen rarely. Moreover, I have not experienced that while using this app. Function runtime crashes can occur due to multiple reasons, such as an exception being thrown in the user code due to network errors. I considered this rare case from the viewpoint that Azure QueueTrigger functions are executed at least once.

Again, I appreciate your feedback and acknowledge that the current implementation might be sufficient for most cases. My intention was to highlight a potential area of improvement to enhance the system's reliability and user experience.

**Comment by jeffputz** [comment]
Notifications are not the source of truth. They didn't even exist until recently. This isn't something I'm going to spend time on.
