### ISSUE TITLE
If you log out while viewing a page requiring a log in ( e.g. private message ) you get an http 403 error page

### ISSUE THREAD

**Issue by WiseyD** [POPWorldMedia/POPForums#338]
If you are logged into a private message ( or any area that requires a log in ), rather than get redirected to /forums (or another friendly page, i.e. 'you are now logged out') you get a http error 403 Access Denied you don't have authorization to view this page.  Would be nice if the log out button redirected the user to the main page, /forums or even a friendly page advising they have been logged out.

**Comment by jeffputz** [comment]
You can configure a 403 page in your app to display whatever you want. I don't think it's really the forum's responsibility to explain the 403, because it depends on the context in which it's running.

**Comment by WiseyD** [comment]
While that's true someone could configure a 403 and who says I haven't created a "403" page to display. However that's not the same as redirecting a user who logs out in a secure area of the forum to a friendly page like the home page for example rather than a 403, this would seem to be a better option. A user shouldn't be getting a 403 just by logging out.

**Comment by jeffputz** [comment]
You're right, a user shouldn't be not given direction, but I'm saying that since the forum is typically not stand-alone, that direction should be deferred to the containing application.

Authorization is not a primary function of the forum, it's just using the bits already in .Net.

**Comment by WiseyD** [comment]
I'm not talking about authorization, I'm talking about bad user experience in the forum, if the user is logged into the forum and is on a page / area that requires them to be logged in order to view it, and they happen to click 'log out' in the forums navbar drop down they will get a 403 access denied as they are still on the page that requires them to be logged in. To avoid the 403 thought a redirect back to the main forum page after logging out would be nice. 

I thought you may want to look at it, but no worries, not asking you to do anything.  I'm quite capable of updating my own site and can update the code I'm using to add a redirect back to '/forums' after the logout. Just trying to be helpful and contribute to in a small way. Thanks for PopForums, keep doing what you do, great job.

**Comment by jeffputz** [comment]
But you _are_ talking about authorization. The framework determines the user is not authorized to access a resource at a specific URL and returns the semantically correct response. I'm not disagreeing with you about what the ideal experience should be, I'm just saying that I don't philosophically agree that the forum app itself should determine what to do, as a redirect response doesn't mean the same thing as a not authorized response.

**Comment by WiseyD** [comment]
redirect of an already "authorized person" logging out, not a un-authorized person accessing a page they are not supposed to be on.
