### ISSUE TITLE
cannot save changes of courses if remove in edit httppost

### ISSUE THREAD

**Issue by ahmedba** [POPWorldMedia/POPForums#45]
Problem
when remove course then click submit not save changes although
it removed from client side by jquery
Details 
in edit view for every employee i need to do changes by remove or add new courses for employee
if i add new courses then click submit button it save what i do
but if i remove course from courses then click submit it will not save courses i removed
so that i need to check what is wrong in my code
my code working without any problem  but only have problem
i cannot save courses removed in database in employeecourse table when click submit 
employeecourse table have Id,EmployeeId,CourseId
jquery remove client side attached with my question 
code 
my code as following 
```
[HttpPost]  
        public ActionResult Edit(EditEmployeeVm model)  
        {  
            var emp = db.Employees.FirstOrDefault(f => f.Id == model.Id);  
            foreach (var couseid in model.CourseIds)  
            {  
                db.EmployeeCourses.Add(new EmployeeCourse { CourseId = couseid, EmployeeId = emp.Id });  
                db.SaveChanges();  
            }  
        
            return View();  
my(custom model) view model using for that  
 public class EditEmployeeVm  
    {  
        public int Id { set; get; }  
        public List<SelectListItem> Courses { get; set; }  
        public int[] CourseIds { set; get; }  
        public List<CourseVm> ExistingCourses { set; get; }  
    }  
    public class CourseVm  
    {  
        public int Id { set; get; }  
        public string Name { set; get; }  
    }  
}  
```
 to show what i need clearly see image below
![course wrong9](https://cloud.githubusercontent.com/assets/20745093/18414402/cc95d66e-77c6-11e6-97ca-904da25be706.jpg)

**Comment by jeffputz** [comment]
I have no idea what this is, but it has nothing to do with POP Forums.
