### ISSUE TITLE
Automatically subscribe to topics you contribute to

### ISSUE THREAD

**Issue by TheYorkshireDev** [POPWorldMedia/POPForums#79]
I think it would be useful to automatically subscribe a user to a topic if they have contributed to it. This includes as a topic author becoming automatically subscribed so you are notified of any subsequent replies. Likewise, if you contribute to a thread you would become subscribed. 

GitHub follows this kind of behaviour, when you contribute to an issue of PR.

**Comment by jeffputz** [comment]
How would you set that up? A profile setting?

**Comment by TheYorkshireDev** [comment]
On the fork of PopForums I manage at work I added a line in `ForumController/PostTopic()` which subscribes the user whenever they post (including author a topic). This is the behaviour GitHub follows but I am aware that if you unsubscribe then post again, you are subscribed again to that topic.

**Comment by jeffputz** [comment]
So there's probably a business rule that says if you have previously pushed unsubscribe that auto-subscribe would not be cool, right? We'd have to store that state info somewhere. What about a checkbox that says "subscribe" next to the submit button, and what if the default state of that checkbox was driven by a profile setting?

**Comment by TheYorkshireDev** [comment]
@jeffputz Sorry for the late reply.

I agree that this should be an opt-in feature at the global forum level especially after your comment in #84. I don't like the idea about having a checkbox next to submit and much prefer the implicit subscription if the forum admin set it, this follows the behaviour of GitHub too. 

I would suggest a `Mute` column (just of type BIT) on the `[pf_SubscribeTopic]`. In this scenario unsubscribing would not remove a row from `[pf_SubscribeTopic]` but toggle the `Mute` value.
With this approach the code in #84 would stay as it is. The Unsubscribe method would be altered to toggle the mute value and the email subscribed users service would just do a check to see if the user has muted the subscription to avoid sending them updates. In addition, if the `MUTE` column is added now the SQL can be added in the `PopForums13to14.sql` migration file.

Your comment on #84 about leaving this task till v-next is understandable however am aware that periods between v-releases have been large in the past and would be interested if you would  be interested in more frequent minor version releases such as a v14.1 once larger features are in?

I am interested to hear your thoughts

**Comment by jeffputz** [comment]
I still need to ship v14.0, and #87 and #82 are currently blocking that. :)

**Comment by TheYorkshireDev** [comment]
Great work with the new release Jeff. I was wondering what your thoughts are on the suggestion of how we could change the subscriptions I outlined above?

**Comment by jeffputz** [comment]
OK... so I'm going to pull this from the v16 release, because I want to revisit notifications in a bigger way, so that they're durable and appear inside the web app. That's a big ask, so I don't want to build something that I might tear down later. This is an important one though, I definitely want to do it!

**Comment by jeffputz** [comment]
Revisiting this... I'm going to remove the email notification functionality, because at least on my sites it's very rarely used. People just don't use email for this much. However, I am going to use a notification system, and this would really key in to that. (#264)
