### ISSUE TITLE
Disable Post Titles

### ISSUE THREAD

**Issue by TheYorkshireDev** [POPWorldMedia/POPForums#81]
Each post has a title and body field, the body is obviously the content of the post but the title of each post is not publicly available anywhere.

Every reply to a post gets a pre-generated title with the format `Re: Title` and this is persisted in the `posts` table within the DB. Since updating the post title does not make any difference in the UI anywhere why allow users to do so and persist in the database? We should disable the field.

<img width="591" alt="screen shot 2018-06-29 at 22 02 34" src="https://user-images.githubusercontent.com/30004860/42114765-2a77e962-7be8-11e8-8e5c-55bbeac3a28a.png">

**Comment by jeffputz** [comment]
Yeah, it shouldn't be there. It's a relic that dates back to some differences in the UI that have been gone for a long time.
