### ISSUE TITLE
login e-mail to name

### ISSUE THREAD

**Issue by EvgGen** [POPWorldMedia/POPForums#89]
Hey. I need to login to the login forum, and not by mail. How to do it?

**Comment by jeffputz** [comment]
This is not an issue.

**Comment by EvgGen** [comment]
I need to use a login for the login not e-mail, but the name

**Comment by jeffputz** [comment]
It uses email to login, not the name.

**Comment by EvgGen** [comment]
The name can not be used in any way? Maybe you can refer to the source code?
