### ISSUE TITLE
Width and height being stripped from photos after resizing in rich text editor

### ISSUE THREAD

**Issue by 0x576f6c6672616d** [POPWorldMedia/POPForums#92]
In TextParsingService.cs it appears that line 201 `text = Regex.Replace(text, @"(<img )(\S+ )*(src="")(\S+)("")( *\S+)*( */?>)", "[image=$4]", RegexOptions.IgnoreCase);` is stripping the new width and height of images that are resized in the rich text editor. I replaced it with `text = Regex.Replace(text, @"(<img )(\S+ )*(src="")(\S+)("".+)(width=""\d*"" height=""\d*"")( *\S+)*( */?>)", "[image=$4 $6]", RegexOptions.IgnoreCase);` I also had to replace the code that parses "ForumCode" back to HTML on line 354. I replaced `text = Regex.Replace(text, @"(\[image=""?)(\S+?)(""?\])", "<img src=\"$2\" />", RegexOptions.IgnoreCase);` with `text = Regex.Replace(text, @"(\[image=""?)(\S+?)(\s+width=""\d*""\s+height=""\d*"")(""?\])","<img src=\"$2\"$3 />", RegexOptions.IgnoreCase);`. Photo resizing appears to work correctly after this; however, I'm not very confident in my Regex skills, and I present it for your consideration. It would be nice if we could limit the maximum size of the inserted photo, similar to the youtube size limit. Not sure if changing TinyMCE settings is the correct way to handle this.

**Comment by jeffputz** [comment]
This is by design. As images have no specific placement in the flow of text, it doesn't make sense to set sizes in them because they aren't meaningful relative to screen size. Instead, they're limited in width by CSS so they don't hang off the screen.

**Comment by 0x576f6c6672616d** [comment]
Maybe the picture resizing ability should be removed. It just seems that it could be confusing for users who resize their images, but then hit submit and find out the image was not actually resized. So width is limited by CSS but images are allowed to have arbitrarily large heights?

**Comment by jeffputz** [comment]
Can TinyMCE be configured to disable the resizing? If so, there's a settings block in the mid-40's of PopForums.js, and you could add it and submit a PR: https://github.com/POPWorldMedia/POPForums/blob/master/src/PopForums.Web/wwwroot/lib/PopForums/PopForums.js
